@baseUrl = http://localhost:1337
@email = mail2rajja@gmail.com
@id = 62bdaee9679930f1d34bf42c


###
GET {{baseUrl}}/api/articles
Authorization: Bearer {{refauth.response.body.access_token}}


###
GET {{baseUrl}}/api/articles/{{id}}
Authorization: Bearer {{refauth.response.body.access_token}}


###
POST {{baseUrl}}/api/articles
Authorization: Bearer {{refauth.response.body.access_token}}
Content-Type: application/json

{
    "title":"Jun 30 Article",
    "author":"John Doe",
    "description":"lorem ipsum dolar sit amet"
}



###
PUT {{baseUrl}}/api/articles/{{id}}
Authorization: Bearer {{refauth.response.body.access_token}}
Content-Type: application/json

{
    "images":[
                {
                    "kind":"thumbnail",
                    "url":"http://habrahabr.ru/images/write-topic.png"
                },
                {
                    "kind":"detail",
                    "url":"http://habrahabr.ru/images/write-topic.png"
                }
            ]
}

# ---------------------------

###
DELETE {{baseUrl}}/api/articles/{{id}}
Authorization: Bearer {{refauth.response.body.access_token}}

###
GET {{baseUrl}}/api/users/info
Authorization: Bearer {{refauth.response.body.access_token}}


# ---------------------------

# get tokens
###
# @name auth
POST {{baseUrl}}/api/oauth/token 
Content-Type: application/json

{
    "grant_type":"password",
    "client_id":"android",
    "client_secret":"SomeRandomCharsAndNumbers",
    "username":"myapi",
    "password":"abc1234"
}

###
# @name refauth
POST {{baseUrl}}/api/oauth/token 
Content-Type: application/json

{
    "grant_type":"refresh_token",
    "client_id":"android",
    "client_secret":"SomeRandomCharsAndNumbers",
    "refresh_token":"{{auth.response.body.refresh_token}}"
}
